##
# This file is part of the pl.wrzasq.commons.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2024 © by Rafał Wrzeszcz - Wrzasq.pl.
##

max_width = 120
newline_style = "Unix"
edition = "2021"
